
architecture: i386

packages:
  kernel: src
  kora_headers: src
  file_systems: src
  drivers_pc: src
  drivers_misc: src
  libc: src
  lgfx: src
  utils: src
  krish: src
  desktop: src
  zlib: v1.2.11
  freetype: v2.10.2
  openlibm: v0.7.0
  libpng: v1.6.37
  pixman: v0.40.0

sources:
  kernel: https://github.com/axfab/kora-kernel
  file_systems: https://github.com/axfab/kora-file-systems
  drivers_pc: https://github.com/axfab/kora-drivers-pc
  drivers_misc: https://github.com/axfab/kora-drivers-misc
  libc: https://github.com/axfab/kora-libc
  lgfx: https://github.com/axfab/kora-lgfx
  utils: https://github.com/axfab/kora-utils
  krish: https://github.com/axfab/kora-krish
  desktop: https://github.com/axfab/kora-desktop


